// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Dataset       string                 `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NLRequest) Reset() {
	*x = NLRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NLRequest) ProtoMessage() {}

func (x *NLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NLRequest.ProtoReflect.Descriptor instead.
func (*NLRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *NLRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *NLRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *NLRequest) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type NLResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PlanJson     string                 `protobuf:"bytes,1,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	RawLlmOutput string                 `protobuf:"bytes,2,opt,name=raw_llm_output,json=rawLlmOutput,proto3" json:"raw_llm_output,omitempty"`
	// Set (with plan_json empty) if nl_to_plan failed validation twice —
	// mirrors CompileResponse.error's "empty fields + error string" shape.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NLResponse) Reset() {
	*x = NLResponse{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NLResponse) ProtoMessage() {}

func (x *NLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NLResponse.ProtoReflect.Descriptor instead.
func (*NLResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *NLResponse) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

func (x *NLResponse) GetRawLlmOutput() string {
	if x != nil {
		return x.RawLlmOutput
	}
	return ""
}

func (x *NLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExplainRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Question       string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	ResultArrowIpc []byte                 `protobuf:"bytes,2,opt,name=result_arrow_ipc,json=resultArrowIpc,proto3" json:"result_arrow_ipc,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ExplainRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ExplainRequest) GetResultArrowIpc() []byte {
	if x != nil {
		return x.ResultArrowIpc
	}
	return nil
}

type ExplainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Explanation   string                 `protobuf:"bytes,1,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ExplainResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\batlas.ai\"b\n" +
	"\tNLRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x18\n" +
	"\adataset\x18\x02 \x01(\tR\adataset\x12\x1f\n" +
	"\vschema_json\x18\x03 \x01(\tR\n" +
	"schemaJson\"e\n" +
	"\n" +
	"NLResponse\x12\x1b\n" +
	"\tplan_json\x18\x01 \x01(\tR\bplanJson\x12$\n" +
	"\x0eraw_llm_output\x18\x02 \x01(\tR\frawLlmOutput\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"V\n" +
	"\x0eExplainRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12(\n" +
	"\x10result_arrow_ipc\x18\x02 \x01(\fR\x0eresultArrowIpc\"3\n" +
	"\x0fExplainResponse\x12 \n" +
	"\vexplanation\x18\x01 \x01(\tR\vexplanation2\x83\x01\n" +
	"\tAIService\x126\n" +
	"\tNLToQuery\x12\x13.atlas.ai.NLRequest\x1a\x14.atlas.ai.NLResponse\x12>\n" +
	"\aExplain\x12\x18.atlas.ai.ExplainRequest\x1a\x19.atlas.ai.ExplainResponseB&Z$atlas/coordinator/internal/aipb;aipbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_proto_goTypes = []any{
	(*NLRequest)(nil),       // 0: atlas.ai.NLRequest
	(*NLResponse)(nil),      // 1: atlas.ai.NLResponse
	(*ExplainRequest)(nil),  // 2: atlas.ai.ExplainRequest
	(*ExplainResponse)(nil), // 3: atlas.ai.ExplainResponse
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: atlas.ai.AIService.NLToQuery:input_type -> atlas.ai.NLRequest
	2, // 1: atlas.ai.AIService.Explain:input_type -> atlas.ai.ExplainRequest
	1, // 2: atlas.ai.AIService.NLToQuery:output_type -> atlas.ai.NLResponse
	3, // 3: atlas.ai.AIService.Explain:output_type -> atlas.ai.ExplainResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
