// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *CompileRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *CompileRequest) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type CompileResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PartialPlanJson string                 `protobuf:"bytes,1,opt,name=partial_plan_json,json=partialPlanJson,proto3" json:"partial_plan_json,omitempty"`
	CombinePlanJson string                 `protobuf:"bytes,2,opt,name=combine_plan_json,json=combinePlanJson,proto3" json:"combine_plan_json,omitempty"` // empty if !needs_combine
	NeedsCombine    bool                   `protobuf:"varint,3,opt,name=needs_combine,json=needsCombine,proto3" json:"needs_combine,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // set (with the fields above empty) if SQL failed to compile
	// Phase 4 (docs/atlas-implementation-spec.md): the plan before any rule
	// rewrites, and after rule rewrites but before the partial/combine split.
	// `POST /explain` returns both; the coordinator threads them through
	// unopened same as the other plan fields.
	LogicalPlanJson   string `protobuf:"bytes,5,opt,name=logical_plan_json,json=logicalPlanJson,proto3" json:"logical_plan_json,omitempty"`
	OptimizedPlanJson string `protobuf:"bytes,6,opt,name=optimized_plan_json,json=optimizedPlanJson,proto3" json:"optimized_plan_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *CompileResponse) GetPartialPlanJson() string {
	if x != nil {
		return x.PartialPlanJson
	}
	return ""
}

func (x *CompileResponse) GetCombinePlanJson() string {
	if x != nil {
		return x.CombinePlanJson
	}
	return ""
}

func (x *CompileResponse) GetNeedsCombine() bool {
	if x != nil {
		return x.NeedsCombine
	}
	return false
}

func (x *CompileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompileResponse) GetLogicalPlanJson() string {
	if x != nil {
		return x.LogicalPlanJson
	}
	return ""
}

func (x *CompileResponse) GetOptimizedPlanJson() string {
	if x != nil {
		return x.OptimizedPlanJson
	}
	return ""
}

type TaskRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PlanJson string                 `protobuf:"bytes,2,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*TaskRequest_File
	//	*TaskRequest_Inline
	Source        isTaskRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

func (x *TaskRequest) GetSource() isTaskRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TaskRequest) GetFile() *FileSource {
	if x != nil {
		if x, ok := x.Source.(*TaskRequest_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *TaskRequest) GetInline() *InlineSource {
	if x != nil {
		if x, ok := x.Source.(*TaskRequest_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

type isTaskRequest_Source interface {
	isTaskRequest_Source()
}

type TaskRequest_File struct {
	File *FileSource `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

type TaskRequest_Inline struct {
	Inline *InlineSource `protobuf:"bytes,4,opt,name=inline,proto3,oneof"`
}

func (*TaskRequest_File) isTaskRequest_Source() {}

func (*TaskRequest_Inline) isTaskRequest_Source() {}

type FileSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"` // empty = all columns
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`   // "" | "atlas" | "parquet" (future: "iceberg")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSource) Reset() {
	*x = FileSource{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSource) ProtoMessage() {}

func (x *FileSource) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSource.ProtoReflect.Descriptor instead.
func (*FileSource) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *FileSource) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileSource) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *FileSource) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type InlineSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each entry is one self-contained Arrow IPC stream (as produced by
	// ResultBatch.arrow_ipc), typically one per upstream partial task.
	ArrowIpcBatches [][]byte `protobuf:"bytes,1,rep,name=arrow_ipc_batches,json=arrowIpcBatches,proto3" json:"arrow_ipc_batches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InlineSource) Reset() {
	*x = InlineSource{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineSource) ProtoMessage() {}

func (x *InlineSource) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineSource.ProtoReflect.Descriptor instead.
func (*InlineSource) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *InlineSource) GetArrowIpcBatches() [][]byte {
	if x != nil {
		return x.ArrowIpcBatches
	}
	return nil
}

type ResultBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArrowIpc      []byte                 `protobuf:"bytes,1,opt,name=arrow_ipc,json=arrowIpc,proto3" json:"arrow_ipc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultBatch) Reset() {
	*x = ResultBatch{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultBatch) ProtoMessage() {}

func (x *ResultBatch) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultBatch.ProtoReflect.Descriptor instead.
func (*ResultBatch) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ResultBatch) GetArrowIpc() []byte {
	if x != nil {
		return x.ArrowIpc
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	InFlightTasks int32                  `protobuf:"varint,2,opt,name=in_flight_tasks,json=inFlightTasks,proto3" json:"in_flight_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetInFlightTasks() int32 {
	if x != nil {
		return x.InFlightTasks
	}
	return 0
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\fatlas.worker\"C\n" +
	"\x0eCompileRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\tR\n" +
	"schemaJson\"\x80\x02\n" +
	"\x0fCompileResponse\x12*\n" +
	"\x11partial_plan_json\x18\x01 \x01(\tR\x0fpartialPlanJson\x12*\n" +
	"\x11combine_plan_json\x18\x02 \x01(\tR\x0fcombinePlanJson\x12#\n" +
	"\rneeds_combine\x18\x03 \x01(\bR\fneedsCombine\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x11logical_plan_json\x18\x05 \x01(\tR\x0flogicalPlanJson\x12.\n" +
	"\x13optimized_plan_json\x18\x06 \x01(\tR\x11optimizedPlanJson\"\xb3\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tplan_json\x18\x02 \x01(\tR\bplanJson\x12.\n" +
	"\x04file\x18\x03 \x01(\v2\x18.atlas.worker.FileSourceH\x00R\x04file\x124\n" +
	"\x06inline\x18\x04 \x01(\v2\x1a.atlas.worker.InlineSourceH\x00R\x06inlineB\b\n" +
	"\x06source\"[\n" +
	"\n" +
	"FileSource\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\":\n" +
	"\fInlineSource\x12*\n" +
	"\x11arrow_ipc_batches\x18\x01 \x03(\fR\x0farrowIpcBatches\"*\n" +
	"\vResultBatch\x12\x1b\n" +
	"\tarrow_ipc\x18\x01 \x01(\fR\barrowIpc\"\x12\n" +
	"\x10HeartbeatRequest\"Q\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12&\n" +
	"\x0fin_flight_tasks\x18\x02 \x01(\x05R\rinFlightTasks2\xec\x01\n" +
	"\rWorkerService\x12F\n" +
	"\aCompile\x12\x1c.atlas.worker.CompileRequest\x1a\x1d.atlas.worker.CompileResponse\x12E\n" +
	"\vExecuteTask\x12\x19.atlas.worker.TaskRequest\x1a\x19.atlas.worker.ResultBatch0\x01\x12L\n" +
	"\tHeartbeat\x12\x1e.atlas.worker.HeartbeatRequest\x1a\x1f.atlas.worker.HeartbeatResponseB.Z,atlas/coordinator/internal/workerpb;workerpbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_worker_proto_goTypes = []any{
	(*CompileRequest)(nil),    // 0: atlas.worker.CompileRequest
	(*CompileResponse)(nil),   // 1: atlas.worker.CompileResponse
	(*TaskRequest)(nil),       // 2: atlas.worker.TaskRequest
	(*FileSource)(nil),        // 3: atlas.worker.FileSource
	(*InlineSource)(nil),      // 4: atlas.worker.InlineSource
	(*ResultBatch)(nil),       // 5: atlas.worker.ResultBatch
	(*HeartbeatRequest)(nil),  // 6: atlas.worker.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 7: atlas.worker.HeartbeatResponse
}
var file_worker_proto_depIdxs = []int32{
	3, // 0: atlas.worker.TaskRequest.file:type_name -> atlas.worker.FileSource
	4, // 1: atlas.worker.TaskRequest.inline:type_name -> atlas.worker.InlineSource
	0, // 2: atlas.worker.WorkerService.Compile:input_type -> atlas.worker.CompileRequest
	2, // 3: atlas.worker.WorkerService.ExecuteTask:input_type -> atlas.worker.TaskRequest
	6, // 4: atlas.worker.WorkerService.Heartbeat:input_type -> atlas.worker.HeartbeatRequest
	1, // 5: atlas.worker.WorkerService.Compile:output_type -> atlas.worker.CompileResponse
	5, // 6: atlas.worker.WorkerService.ExecuteTask:output_type -> atlas.worker.ResultBatch
	7, // 7: atlas.worker.WorkerService.Heartbeat:output_type -> atlas.worker.HeartbeatResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[2].OneofWrappers = []any{
		(*TaskRequest_File)(nil),
		(*TaskRequest_Inline)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
