// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dataset struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SchemaJson        string                 `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	CurrentSnapshotId string                 `protobuf:"bytes,4,opt,name=current_snapshot_id,json=currentSnapshotId,proto3" json:"current_snapshot_id,omitempty"` // empty if no snapshot committed yet
	CreatedAt         string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                           // RFC3339
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Dataset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dataset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dataset) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

func (x *Dataset) GetCurrentSnapshotId() string {
	if x != nil {
		return x.CurrentSnapshotId
	}
	return ""
}

func (x *Dataset) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Snapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DatasetId        string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	ParentSnapshotId string                 `protobuf:"bytes,3,opt,name=parent_snapshot_id,json=parentSnapshotId,proto3" json:"parent_snapshot_id,omitempty"` // empty for the first snapshot
	ManifestListPath string                 `protobuf:"bytes,4,opt,name=manifest_list_path,json=manifestListPath,proto3" json:"manifest_list_path,omitempty"`
	Operation        string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"` // "append" | "overwrite" | "delete"
	SummaryJson      string                 `protobuf:"bytes,6,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snapshot) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *Snapshot) GetParentSnapshotId() string {
	if x != nil {
		return x.ParentSnapshotId
	}
	return ""
}

func (x *Snapshot) GetManifestListPath() string {
	if x != nil {
		return x.ManifestListPath
	}
	return ""
}

func (x *Snapshot) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Snapshot) GetSummaryJson() string {
	if x != nil {
		return x.SummaryJson
	}
	return ""
}

func (x *Snapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Manifest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SnapshotId          string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	FilePath            string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	PartitionValuesJson string                 `protobuf:"bytes,4,opt,name=partition_values_json,json=partitionValuesJson,proto3" json:"partition_values_json,omitempty"` // {column: value}
	RowCount            int64                  `protobuf:"varint,5,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	FileSizeBytes       int64                  `protobuf:"varint,6,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	ColumnStatsJson     string                 `protobuf:"bytes,7,opt,name=column_stats_json,json=columnStatsJson,proto3" json:"column_stats_json,omitempty"` // {column: {min, max, null_count}}
	Format              string                 `protobuf:"bytes,8,opt,name=format,proto3" json:"format,omitempty"`                                            // "atlas" | "parquet" (future: "iceberg")
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Manifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manifest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *Manifest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Manifest) GetPartitionValuesJson() string {
	if x != nil {
		return x.PartitionValuesJson
	}
	return ""
}

func (x *Manifest) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *Manifest) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *Manifest) GetColumnStatsJson() string {
	if x != nil {
		return x.ColumnStatsJson
	}
	return ""
}

func (x *Manifest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type CreateDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatasetRequest) Reset() {
	*x = CreateDatasetRequest{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatasetRequest) ProtoMessage() {}

func (x *CreateDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatasetRequest.ProtoReflect.Descriptor instead.
func (*CreateDatasetRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDatasetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatasetRequest) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type GetDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetRequest) Reset() {
	*x = GetDatasetRequest{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetRequest) ProtoMessage() {}

func (x *GetDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetRequest.ProtoReflect.Descriptor instead.
func (*GetDatasetRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetDatasetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*Dataset             `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListDatasetsResponse) GetDatasets() []*Dataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type CommitSnapshotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DatasetId        string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	ManifestListPath string                 `protobuf:"bytes,2,opt,name=manifest_list_path,json=manifestListPath,proto3" json:"manifest_list_path,omitempty"`
	Operation        string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	SummaryJson      string                 `protobuf:"bytes,4,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"`
	Manifests        []*ManifestInput       `protobuf:"bytes,5,rep,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommitSnapshotRequest) Reset() {
	*x = CommitSnapshotRequest{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSnapshotRequest) ProtoMessage() {}

func (x *CommitSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CommitSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *CommitSnapshotRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *CommitSnapshotRequest) GetManifestListPath() string {
	if x != nil {
		return x.ManifestListPath
	}
	return ""
}

func (x *CommitSnapshotRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CommitSnapshotRequest) GetSummaryJson() string {
	if x != nil {
		return x.SummaryJson
	}
	return ""
}

func (x *CommitSnapshotRequest) GetManifests() []*ManifestInput {
	if x != nil {
		return x.Manifests
	}
	return nil
}

type ManifestInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FilePath            string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	PartitionValuesJson string                 `protobuf:"bytes,2,opt,name=partition_values_json,json=partitionValuesJson,proto3" json:"partition_values_json,omitempty"`
	RowCount            int64                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	FileSizeBytes       int64                  `protobuf:"varint,4,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	ColumnStatsJson     string                 `protobuf:"bytes,5,opt,name=column_stats_json,json=columnStatsJson,proto3" json:"column_stats_json,omitempty"`
	Format              string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"` // "atlas" | "parquet" (future: "iceberg")
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ManifestInput) Reset() {
	*x = ManifestInput{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestInput) ProtoMessage() {}

func (x *ManifestInput) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestInput.ProtoReflect.Descriptor instead.
func (*ManifestInput) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *ManifestInput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ManifestInput) GetPartitionValuesJson() string {
	if x != nil {
		return x.PartitionValuesJson
	}
	return ""
}

func (x *ManifestInput) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *ManifestInput) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *ManifestInput) GetColumnStatsJson() string {
	if x != nil {
		return x.ColumnStatsJson
	}
	return ""
}

func (x *ManifestInput) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetName   string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *GetSnapshotRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

type ListManifestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManifestsRequest) Reset() {
	*x = ListManifestsRequest{}
	mi := &file_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManifestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManifestsRequest) ProtoMessage() {}

func (x *ListManifestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManifestsRequest.ProtoReflect.Descriptor instead.
func (*ListManifestsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *ListManifestsRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type ListManifestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifests     []*Manifest            `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManifestsResponse) Reset() {
	*x = ListManifestsResponse{}
	mi := &file_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManifestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManifestsResponse) ProtoMessage() {}

func (x *ListManifestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManifestsResponse.ProtoReflect.Descriptor instead.
func (*ListManifestsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *ListManifestsResponse) GetManifests() []*Manifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\ratlas.catalog\"\x9d\x01\n" +
	"\aDataset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vschema_json\x18\x03 \x01(\tR\n" +
	"schemaJson\x12.\n" +
	"\x13current_snapshot_id\x18\x04 \x01(\tR\x11currentSnapshotId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xf5\x01\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12,\n" +
	"\x12parent_snapshot_id\x18\x03 \x01(\tR\x10parentSnapshotId\x12,\n" +
	"\x12manifest_list_path\x18\x04 \x01(\tR\x10manifestListPath\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12!\n" +
	"\fsummary_json\x18\x06 \x01(\tR\vsummaryJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\x95\x02\n" +
	"\bManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x122\n" +
	"\x15partition_values_json\x18\x04 \x01(\tR\x13partitionValuesJson\x12\x1b\n" +
	"\trow_count\x18\x05 \x01(\x03R\browCount\x12&\n" +
	"\x0ffile_size_bytes\x18\x06 \x01(\x03R\rfileSizeBytes\x12*\n" +
	"\x11column_stats_json\x18\a \x01(\tR\x0fcolumnStatsJson\x12\x16\n" +
	"\x06format\x18\b \x01(\tR\x06format\"K\n" +
	"\x14CreateDatasetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\tR\n" +
	"schemaJson\"'\n" +
	"\x11GetDatasetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13ListDatasetsRequest\"J\n" +
	"\x14ListDatasetsResponse\x122\n" +
	"\bdatasets\x18\x01 \x03(\v2\x16.atlas.catalog.DatasetR\bdatasets\"\xe1\x01\n" +
	"\x15CommitSnapshotRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12,\n" +
	"\x12manifest_list_path\x18\x02 \x01(\tR\x10manifestListPath\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12!\n" +
	"\fsummary_json\x18\x04 \x01(\tR\vsummaryJson\x12:\n" +
	"\tmanifests\x18\x05 \x03(\v2\x1c.atlas.catalog.ManifestInputR\tmanifests\"\xe9\x01\n" +
	"\rManifestInput\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x122\n" +
	"\x15partition_values_json\x18\x02 \x01(\tR\x13partitionValuesJson\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x03R\browCount\x12&\n" +
	"\x0ffile_size_bytes\x18\x04 \x01(\x03R\rfileSizeBytes\x12*\n" +
	"\x11column_stats_json\x18\x05 \x01(\tR\x0fcolumnStatsJson\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"7\n" +
	"\x12GetSnapshotRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\"7\n" +
	"\x14ListManifestsRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"N\n" +
	"\x15ListManifestsResponse\x125\n" +
	"\tmanifests\x18\x01 \x03(\v2\x17.atlas.catalog.ManifestR\tmanifests2\xfe\x03\n" +
	"\x0eCatalogService\x12L\n" +
	"\rCreateDataset\x12#.atlas.catalog.CreateDatasetRequest\x1a\x16.atlas.catalog.Dataset\x12F\n" +
	"\n" +
	"GetDataset\x12 .atlas.catalog.GetDatasetRequest\x1a\x16.atlas.catalog.Dataset\x12W\n" +
	"\fListDatasets\x12\".atlas.catalog.ListDatasetsRequest\x1a#.atlas.catalog.ListDatasetsResponse\x12O\n" +
	"\x0eCommitSnapshot\x12$.atlas.catalog.CommitSnapshotRequest\x1a\x17.atlas.catalog.Snapshot\x12P\n" +
	"\x12GetCurrentSnapshot\x12!.atlas.catalog.GetSnapshotRequest\x1a\x17.atlas.catalog.Snapshot\x12Z\n" +
	"\rListManifests\x12#.atlas.catalog.ListManifestsRequest\x1a$.atlas.catalog.ListManifestsResponseB0Z.atlas/coordinator/internal/catalogpb;catalogpbb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_catalog_proto_goTypes = []any{
	(*Dataset)(nil),               // 0: atlas.catalog.Dataset
	(*Snapshot)(nil),              // 1: atlas.catalog.Snapshot
	(*Manifest)(nil),              // 2: atlas.catalog.Manifest
	(*CreateDatasetRequest)(nil),  // 3: atlas.catalog.CreateDatasetRequest
	(*GetDatasetRequest)(nil),     // 4: atlas.catalog.GetDatasetRequest
	(*ListDatasetsRequest)(nil),   // 5: atlas.catalog.ListDatasetsRequest
	(*ListDatasetsResponse)(nil),  // 6: atlas.catalog.ListDatasetsResponse
	(*CommitSnapshotRequest)(nil), // 7: atlas.catalog.CommitSnapshotRequest
	(*ManifestInput)(nil),         // 8: atlas.catalog.ManifestInput
	(*GetSnapshotRequest)(nil),    // 9: atlas.catalog.GetSnapshotRequest
	(*ListManifestsRequest)(nil),  // 10: atlas.catalog.ListManifestsRequest
	(*ListManifestsResponse)(nil), // 11: atlas.catalog.ListManifestsResponse
}
var file_catalog_proto_depIdxs = []int32{
	0,  // 0: atlas.catalog.ListDatasetsResponse.datasets:type_name -> atlas.catalog.Dataset
	8,  // 1: atlas.catalog.CommitSnapshotRequest.manifests:type_name -> atlas.catalog.ManifestInput
	2,  // 2: atlas.catalog.ListManifestsResponse.manifests:type_name -> atlas.catalog.Manifest
	3,  // 3: atlas.catalog.CatalogService.CreateDataset:input_type -> atlas.catalog.CreateDatasetRequest
	4,  // 4: atlas.catalog.CatalogService.GetDataset:input_type -> atlas.catalog.GetDatasetRequest
	5,  // 5: atlas.catalog.CatalogService.ListDatasets:input_type -> atlas.catalog.ListDatasetsRequest
	7,  // 6: atlas.catalog.CatalogService.CommitSnapshot:input_type -> atlas.catalog.CommitSnapshotRequest
	9,  // 7: atlas.catalog.CatalogService.GetCurrentSnapshot:input_type -> atlas.catalog.GetSnapshotRequest
	10, // 8: atlas.catalog.CatalogService.ListManifests:input_type -> atlas.catalog.ListManifestsRequest
	0,  // 9: atlas.catalog.CatalogService.CreateDataset:output_type -> atlas.catalog.Dataset
	0,  // 10: atlas.catalog.CatalogService.GetDataset:output_type -> atlas.catalog.Dataset
	6,  // 11: atlas.catalog.CatalogService.ListDatasets:output_type -> atlas.catalog.ListDatasetsResponse
	1,  // 12: atlas.catalog.CatalogService.CommitSnapshot:output_type -> atlas.catalog.Snapshot
	1,  // 13: atlas.catalog.CatalogService.GetCurrentSnapshot:output_type -> atlas.catalog.Snapshot
	11, // 14: atlas.catalog.CatalogService.ListManifests:output_type -> atlas.catalog.ListManifestsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
