# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ai_pb2 as ai__pb2


class AIServiceStub(object):
    """The AI service (Python, docs/atlas-implementation-spec.md Phase 6) turns a
    natural-language question into the same LogicalPlan shape SQL compiles to.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NLToQuery = channel.unary_unary(
                '/atlas.ai.AIService/NLToQuery',
                request_serializer=ai__pb2.NLRequest.SerializeToString,
                response_deserializer=ai__pb2.NLResponse.FromString,
                )
        self.Explain = channel.unary_unary(
                '/atlas.ai.AIService/Explain',
                request_serializer=ai__pb2.ExplainRequest.SerializeToString,
                response_deserializer=ai__pb2.ExplainResponse.FromString,
                )


class AIServiceServicer(object):
    """The AI service (Python, docs/atlas-implementation-spec.md Phase 6) turns a
    natural-language question into the same LogicalPlan shape SQL compiles to.
    """

    def NLToQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NLToQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.NLToQuery,
                    request_deserializer=ai__pb2.NLRequest.FromString,
                    response_serializer=ai__pb2.NLResponse.SerializeToString,
            ),
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=ai__pb2.ExplainRequest.FromString,
                    response_serializer=ai__pb2.ExplainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atlas.ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AIService(object):
    """The AI service (Python, docs/atlas-implementation-spec.md Phase 6) turns a
    natural-language question into the same LogicalPlan shape SQL compiles to.
    """

    @staticmethod
    def NLToQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request, target, '/atlas.ai.AIService/NLToQuery',
            ai__pb2.NLRequest.SerializeToString,
            ai__pb2.NLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request, target, '/atlas.ai.AIService/Explain',
            ai__pb2.ExplainRequest.SerializeToString,
            ai__pb2.ExplainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
