# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x08\x61tlas.ai\"C\n\tNLRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x13\n\x0bschema_json\x18\x03 \x01(\t\"F\n\nNLResponse\x12\x11\n\tplan_json\x18\x01 \x01(\t\x12\x16\n\x0eraw_llm_output\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"<\n\x0e\x45xplainRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x18\n\x10result_arrow_ipc\x18\x02 \x01(\x0c\"&\n\x0f\x45xplainResponse\x12\x13\n\x0b\x65xplanation\x18\x01 \x01(\t\"/\n\x16NarrateFindingsRequest\x12\x15\n\rfindings_json\x18\x01 \x01(\t\",\n\x17NarrateFindingsResponse\x12\x11\n\tnarrative\x18\x01 \x01(\t\"D\n\x17SuggestQuestionsRequest\x12\x13\n\x0bschema_json\x18\x01 \x01(\t\x12\x14\n\x0csummary_json\x18\x02 \x01(\t\"-\n\x18SuggestQuestionsResponse\x12\x11\n\tquestions\x18\x01 \x03(\t2\xb6\x02\n\tAIService\x12\x36\n\tNLToQuery\x12\x13.atlas.ai.NLRequest\x1a\x14.atlas.ai.NLResponse\x12>\n\x07\x45xplain\x12\x18.atlas.ai.ExplainRequest\x1a\x19.atlas.ai.ExplainResponse\x12V\n\x0fNarrateFindings\x12 .atlas.ai.NarrateFindingsRequest\x1a!.atlas.ai.NarrateFindingsResponse\x12Y\n\x10SuggestQuestions\x12!.atlas.ai.SuggestQuestionsRequest\x1a\".atlas.ai.SuggestQuestionsResponseB&Z$atlas/coordinator/internal/aipb;aipbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$atlas/coordinator/internal/aipb;aipb'
  _globals['_NLREQUEST']._serialized_start=22
  _globals['_NLREQUEST']._serialized_end=89
  _globals['_NLRESPONSE']._serialized_start=91
  _globals['_NLRESPONSE']._serialized_end=161
  _globals['_EXPLAINREQUEST']._serialized_start=163
  _globals['_EXPLAINREQUEST']._serialized_end=223
  _globals['_EXPLAINRESPONSE']._serialized_start=225
  _globals['_EXPLAINRESPONSE']._serialized_end=263
  _globals['_NARRATEFINDINGSREQUEST']._serialized_start=265
  _globals['_NARRATEFINDINGSREQUEST']._serialized_end=312
  _globals['_NARRATEFINDINGSRESPONSE']._serialized_start=314
  _globals['_NARRATEFINDINGSRESPONSE']._serialized_end=358
  _globals['_SUGGESTQUESTIONSREQUEST']._serialized_start=360
  _globals['_SUGGESTQUESTIONSREQUEST']._serialized_end=428
  _globals['_SUGGESTQUESTIONSRESPONSE']._serialized_start=430
  _globals['_SUGGESTQUESTIONSRESPONSE']._serialized_end=475
  _globals['_AISERVICE']._serialized_start=478
  _globals['_AISERVICE']._serialized_end=788
# @@protoc_insertion_point(module_scope)
