# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """The AI service (Python, docs/atlas-implementation-spec.md Phase 6) turns a
    natural-language question into the same LogicalPlan shape SQL compiles to.
    NLResponse carries that plan as `plan_json` — a JSON string matching
    atlas_query::plan::LogicalPlan's serde external-tagging (see
    proto/plan.proto's header) — not an embedded LogicalPlan message, so the
    coordinator can hand it straight to WorkerService.CompileFromPlan
    (proto/worker.proto) exactly like it already threads
    Compile's *_plan_json fields through unopened. The coordinator fetches
    schema_json itself (CatalogService.GetDataset) and passes it in, the same
    way it already does for the SQL path's CompileRequest — the AI service
    never needs its own catalog client.

    Explain narrates an already-executed result (Arrow IPC bytes) in plain
    English — the LLM never sees raw source data, only a result set the
    engine already produced.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NLToQuery = channel.unary_unary(
                '/atlas.ai.AIService/NLToQuery',
                request_serializer=ai__pb2.NLRequest.SerializeToString,
                response_deserializer=ai__pb2.NLResponse.FromString,
                _registered_method=True)
        self.Explain = channel.unary_unary(
                '/atlas.ai.AIService/Explain',
                request_serializer=ai__pb2.ExplainRequest.SerializeToString,
                response_deserializer=ai__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.NarrateFindings = channel.unary_unary(
                '/atlas.ai.AIService/NarrateFindings',
                request_serializer=ai__pb2.NarrateFindingsRequest.SerializeToString,
                response_deserializer=ai__pb2.NarrateFindingsResponse.FromString,
                _registered_method=True)
        self.SuggestQuestions = channel.unary_unary(
                '/atlas.ai.AIService/SuggestQuestions',
                request_serializer=ai__pb2.SuggestQuestionsRequest.SerializeToString,
                response_deserializer=ai__pb2.SuggestQuestionsResponse.FromString,
                _registered_method=True)


class AIServiceServicer:
    """The AI service (Python, docs/atlas-implementation-spec.md Phase 6) turns a
    natural-language question into the same LogicalPlan shape SQL compiles to.
    NLResponse carries that plan as `plan_json` — a JSON string matching
    atlas_query::plan::LogicalPlan's serde external-tagging (see
    proto/plan.proto's header) — not an embedded LogicalPlan message, so the
    coordinator can hand it straight to WorkerService.CompileFromPlan
    (proto/worker.proto) exactly like it already threads
    Compile's *_plan_json fields through unopened. The coordinator fetches
    schema_json itself (CatalogService.GetDataset) and passes it in, the same
    way it already does for the SQL path's CompileRequest — the AI service
    never needs its own catalog client.

    Explain narrates an already-executed result (Arrow IPC bytes) in plain
    English — the LLM never sees raw source data, only a result set the
    engine already produced.

    """

    def NLToQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NarrateFindings(self, request, context):
        """Phase 7 (AI Analyst): narrates a dataset's already-computed structured
        findings (from atlas-insights, via the coordinator's summary/insights
        pipeline) in plain English — same "engine is source of truth" boundary
        as Explain: the LLM narrates numbers that already exist, it never
        invents them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestQuestions(self, request, context):
        """Generates candidate questions for a dataset and returns only the ones
        that actually produce a valid plan when run back through NLToQuery's
        underlying nl_to_plan — every returned question is guaranteed
        answerable, not just plausible-sounding.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NLToQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.NLToQuery,
                    request_deserializer=ai__pb2.NLRequest.FromString,
                    response_serializer=ai__pb2.NLResponse.SerializeToString,
            ),
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=ai__pb2.ExplainRequest.FromString,
                    response_serializer=ai__pb2.ExplainResponse.SerializeToString,
            ),
            'NarrateFindings': grpc.unary_unary_rpc_method_handler(
                    servicer.NarrateFindings,
                    request_deserializer=ai__pb2.NarrateFindingsRequest.FromString,
                    response_serializer=ai__pb2.NarrateFindingsResponse.SerializeToString,
            ),
            'SuggestQuestions': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestQuestions,
                    request_deserializer=ai__pb2.SuggestQuestionsRequest.FromString,
                    response_serializer=ai__pb2.SuggestQuestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atlas.ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atlas.ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """The AI service (Python, docs/atlas-implementation-spec.md Phase 6) turns a
    natural-language question into the same LogicalPlan shape SQL compiles to.
    NLResponse carries that plan as `plan_json` — a JSON string matching
    atlas_query::plan::LogicalPlan's serde external-tagging (see
    proto/plan.proto's header) — not an embedded LogicalPlan message, so the
    coordinator can hand it straight to WorkerService.CompileFromPlan
    (proto/worker.proto) exactly like it already threads
    Compile's *_plan_json fields through unopened. The coordinator fetches
    schema_json itself (CatalogService.GetDataset) and passes it in, the same
    way it already does for the SQL path's CompileRequest — the AI service
    never needs its own catalog client.

    Explain narrates an already-executed result (Arrow IPC bytes) in plain
    English — the LLM never sees raw source data, only a result set the
    engine already produced.

    """

    @staticmethod
    def NLToQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.ai.AIService/NLToQuery',
            ai__pb2.NLRequest.SerializeToString,
            ai__pb2.NLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.ai.AIService/Explain',
            ai__pb2.ExplainRequest.SerializeToString,
            ai__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NarrateFindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.ai.AIService/NarrateFindings',
            ai__pb2.NarrateFindingsRequest.SerializeToString,
            ai__pb2.NarrateFindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestQuestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.ai.AIService/SuggestQuestions',
            ai__pb2.SuggestQuestionsRequest.SerializeToString,
            ai__pb2.SuggestQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
